---
title: scannedmedia
timezone: America/Los_Angeles


baseurl: "/scannedmedia"

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  portfolio:
    title: Works
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    thumb_image: ''
    image: ''
    caption: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: works
  values:
    layout: work
    project_type: ''
    date: ''
    header_image: ''
    caption: ''
