---
title: scannedmedia
timezone: America/Los_Angeles
collections:
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    thumb image: ''
    image: ''
    caption: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: portfolio
  values:
    layout: portfolio
    project type: ['','']
    header image: ''
    caption: ''
permalink: pretty
