---
title: scannedmedia
timezone: America/Los_Angeles
collections:
  work:
    title: Our Work
    output: true
    image: "/uploads/photo-1432888498266-38ffec3eaf0a.png"
    heading: A bit about us, and our clients.
  posts:
    title: Posts
    output: true
    heading: Have you read our latest blog posts?
  services:
    title: Services
    output: true
    heading: Our Services
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: John Doe
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: work
  values:
    layout: works
    subtitle: branding + identity
head-image: "/uploads/cole-sagerArtboard-4-bg-image-.jpg"
section:
- catagory: '01'
  title: logo
  subtitle: be the impact
- catagory: '02'
  title: fonts
  subtitle: logo and collateral
- catagory: '02'
  title: fonts
  subtitle: logo and collateral
  columns:
    head-image:
      column-size: is-12
      image: "/uploads/cole-sagerArtboard-4-bg-image-.jpg"
    body-content:
      column-size: is-12
      image: "/uploads/cole-sagerArtboard-5-bg-image-.jpg"
    logo-:
      column-size: is-6
      title: 1
      subtitle: logo
      para: Be The Impact
    logo-image1:
      column-size: is-6
      image: 
    logo-image2:
      column-size: is-6
      image: 
    logo-image3:
      column-size: is-12
      image: 
    font-grid:
      column-size: is-6
      image: 
    font:
      column-size: is-6
      title: 2
      subtitle: font
      para: supporting type
    font-image1:
      column-size: is-6
      image: 
    font-image2:
      column-size: is-6
      image: 
    collateral:
      column-size: is-12
      title: 3
      subtitle: collateral
      para: Additional Material
- scope:
    path: ''
    type: services
  values:
    title: Apps
    button: learn more
    image: 
- scope:
    path: ''
    type: testimonials
  values:
    author: John Doe
permalink: pretty
url: https://www.scannedmedia.siteleaf.net
menu:
- title: work
  url: "/work/"
- title: blog
  url: "/blog/"
- title: hire us
  url: "/contact-us/"
sass:
  sass_dir: _sass
logo: "/uploads/SM-logo-horizontal-color.svg"
