---
title: scannedmedia
timezone: America/Los_Angeles
collections:
  work:
    title: Our Work
    output: true
    image: "/uploads/photo-1432888498266-38ffec3eaf0a.png"
    heading: A bit about us, and our clients.
  posts:
    title: Posts
    output: true
    heading: Have you read our latest blog posts?
  services:
    title: Services
    output: true
    heading: Our Services
  testimonials:
    title: Testimonials
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
url: https://www.scannedmedia.siteleaf.net
menu:
  - title: work
    url: "/work/"
  - title: blog
    url: "/blog/"
  - title: hire us
    url: "/contact-us/"
    
sass:
  sass_dir: _sass
logo: "/uploads/SM-logo-horizontal-color.svg"
